# Generated by Django 2.2.16 on 2022-04-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.CharField(default='<Узелок>', max_length=255),
        ),
    ]
